### PR TITLE
fix travis builds

### PR DESCRIPTION
**Pull request by falkenhawk**
swtich php 5.4 and 5.5 to dist: trusty

I haven't found a way to block `composer self-update` from updating to v2 yet.

### CODE REVIEW

**Comment by glensc** [comment]
you can `composer self-update --1` after it has updated by travis

**Comment by falkenhawk** [comment]
> 
> 
> you can `composer self-update --1` after it has updated by travis

the thing is the build fails before it gets to the user-defined commands :(

**Comment by glensc** [comment]
you need to replace the "install" step:
- https://docs.travis-ci.com/user/job-lifecycle/#customizing-the-installation-phase

**Comment by falkenhawk** [comment]
Well it can't even go down to v1.0 because it's stuck on that PEAR error 🙈
image

**Comment by falkenhawk** [comment]
I've found a way to roll composer back to v1,
now I am getting random failures but only on 5.3/5.4/5.5 builds
```
 [Composer\Downloader\TransportException]  

  Peer fingerprint did not match   
```
🤷‍♂️

**Comment by glensc** [comment]
yeah. perhaps it's time to switch to github actions. I've done so in two of my projects:
- https://github.com/perftools/xhgui/pull/366
- https://github.com/eventum/eventum/pull/961

for me the job queue was too long, even the Travis status reporting stopped working, which was a very hard push to move forward

**Comment by falkenhawk** [comment]
@glensc thank you for all the tips!
As much as I like GHA, I don't have time on my hands to migrate this repo.

I found a workaround with `travis_retry`
https://gitlab.devworks.gr/wordpress/wpcs/commit/dcd352582f3dc2b0e94d362acb24d1ab5623226c
https://docs.travis-ci.com/user/common-build-problems/#travis_retry

This should do it for now.

**Pull request merged**
