### PR TITLE
Made Php 8.1 Compatiable

### PR DESCRIPTION
**Pull request by jack-worman**

### CODE REVIEW

**Comment by glensc** [comment]
CI fails, so this is a Draft?

**Comment by glensc** [comment]
perhaps rebase (for example 9a3de06d3c547f2a03ef5aa432f844603ff5a405 should be squashed with 9a3de06d3c547f2a03ef5aa432f844603ff5a405) and force push. then the travis build failure will go away as afaik it stopped running after all.

**Comment by glensc** [comment]
I see some force push happened, but unclear what exactly. my suggestions weren't performed that I see.

the commits were still not joined to one, i.e this commit message is wrong:
- [`9a3de06` (#5)](https://github.com/zf1s/phpunit/pull/5/commits/9a3de06d3c547f2a03ef5aa432f844603ff5a405)

it should be joined (git squash without preserving message or git fixup) to:
- [`66f827c` (#5)](https://github.com/zf1s/phpunit/pull/5/commits/66f827c0d795f26f2474c3faeb54127251dfe1a0)

and it didn't made travis error go away.

**Comment by glensc** [comment]
also, rebase to `origin/master` (https://github.com/zf1s/phpunit) is needed:

> This branch has conflicts that must be resolved

**Comment by glensc** [comment]
conflicts seem to toe step on @partikus  changes from #8

**Comment by partikus** [comment]
@glensc I've pushed with force by mistake. Then I've reverted changes from @jack-worman and pushed them back (including unresolved conflicts). I switched to custom branch then. 
Sorry for the mess 😢

**Comment by glensc** [comment]
@partikus i've took the initiative and split/merge the commits and created new pr:
- https://github.com/zf1s/phpunit/pull/11

I think this (https://github.com/zf1s/phpunit/pull/5) can be closed

**Comment by glensc** [comment]
ok, seems @partikus you have created a new version of this pull request:
- https://github.com/zf1s/phpunit/pull/9

since you didn't write about it here, I had no ideas, I already managed to create my own version:
- https://github.com/zf1s/phpunit/pull/11

**Comment by falkenhawk** [comment]
closing in favor of #9.

**Pull request closed without merging**
